# 课时44 Eager模式代码演示与张量

In [1]:
import pandas as pd
import numpy as np
import seaborn as sb
sb.set_style('darkgrid')
# pathlib相比os.path更好用
import pathlib
import random
import matplotlib.pyplot as plt
import tensorflow as tf
import glob
print('Tensorflow Version:', tf.__version__)

Tensorflow Version: 2.0.0


In [2]:
# TensorFlow2.0默认就是eager模式
tf.executing_eagerly()

True

In [7]:
x = [[2,]]
m = tf.matmul(x, x)
# 需要注意的是张量与ndarray的区别之一是：张量(Tensor)是不可变的对象，
# 且张量不仅可以存储在内存中，还可以存储在GPU的显存中
print(m)
m.numpy()

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


array([[4]])

In [10]:
a = tf.constant([[1, 2],
                 [3, 4]])
a.numpy()

array([[1, 2],
       [3, 4]])

In [11]:
b = tf.add(a, 1)
b

<tf.Tensor: id=19, shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [16]:
d = np.array([[5, 6],
             [7, 8]])
d

array([[5, 6],
       [7, 8]])

In [18]:
(a + b).numpy()

array([[3, 5],
       [7, 9]])

In [12]:
c = tf.multiply(a, b)
c

<tf.Tensor: id=20, shape=(2, 2), dtype=int32, numpy=
array([[ 2,  6],
       [12, 20]])>

In [13]:
num = tf.convert_to_tensor(10)
num

<tf.Tensor: id=21, shape=(), dtype=int32, numpy=10>

In [19]:
float(num)

10.0

In [14]:
# 当使用Python的运算的时候，它会把Tensor对象转换为Python对象
for i in range(num.numpy()):
    i = tf.constant(i)
    if int(i % 2) == 0:
        print('even')
    else:
        print('odd')

even
odd
even
odd
even
odd
even
odd
even
odd
